(rule
 (target callsite_loc.ml)
 (deps callsite_loc.412.ml)
 (enabled_if
  (>= %{ocaml_version} 4.12.0))
 (action
  (copy %{deps} %{target})))

(rule
 (target callsite_loc.ml)
 (enabled_if
  (< %{ocaml_version} 4.12.0))
 (action
  (write-file
   %{target}
   "let get ?__FUNCTION__ () =\n  ignore __FUNCTION__;\n  None\n")))


(rule
 (target c_library_flags.sexp)
 (enabled_if (= %{os_type} Win32))
 (action
  (write-file %{target} "(-ldbghelp)")))

(rule
 (target c_library_flags.sexp)
 (enabled_if (<> %{os_type} Win32))
 (action
  (write-file %{target} "()")))

(library
 (name alcotest_engine)
 (public_name alcotest.engine)
 (foreign_stubs
  (language c)
  (names stack_error_reporter))
  (c_library_flags (:standard (:include c_library_flags.sexp)))
 (libraries
  alcotest.stdlib_ext
  fmt
  astring
  cmdliner
  fmt.cli
  re
  stdlib-shims
  uutf)
 (preprocess future_syntax))
